import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/server/guards/rbac";
import { prisma } from "@/lib/prisma";
import PDFDocument from "pdfkit";
import { logError } from "@/lib/logger";

export async function GET(req: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user || !user.workerId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const month = searchParams.get("month"); // YYYY-MM format

    if (!month || !/^\d{4}-\d{2}$/.test(month)) {
      return NextResponse.json({ error: "month parameter required (YYYY-MM)" }, { status: 400 });
    }

    const [year, mon] = month.split("-").map(Number);
    const periodStart = new Date(year, mon - 1, 1);
    const periodEnd = new Date(year, mon, 0, 23, 59, 59);

    const worker = await prisma.worker.findUnique({
      where: { id: user.workerId },
      select: {
        user: { select: { name: true, email: true } },
        workforceAccount: { select: { displayName: true, type: true } },
      },
    });

    if (!worker) {
      return NextResponse.json({ error: "Worker not found" }, { status: 404 });
    }

    const jobs = await prisma.job.findMany({
      where: {
        assignedWorkerId: user.workerId,
        status: { in: ["APPROVED_PAYABLE", "PAID"] },
        scheduledStart: { gte: periodStart, lte: periodEnd },
      },
      select: {
        scheduledStart: true,
        payoutAmountCents: true,
        status: true,
        site: { select: { name: true } },
      },
      orderBy: { scheduledStart: "asc" },
    });

    const totalCents = jobs.reduce((s, j) => s + j.payoutAmountCents, 0);
    const paidCents = jobs.filter((j) => j.status === "PAID").reduce((s, j) => s + j.payoutAmountCents, 0);

    const doc = new PDFDocument({ margin: 50, size: "LETTER" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    const done = new Promise<Buffer>((resolve, reject) => {
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (err) => reject(err));
    });

    // Header
    doc.fontSize(18).font("Helvetica-Bold").text("BLVCKSHELL", { align: "left" });
    doc.fontSize(10).font("Helvetica").text("Pay Statement", { align: "left" });
    doc.moveDown(1);

    // Worker info
    doc.fontSize(10);
    doc.text(`Worker: ${worker.user.name}`);
    doc.text(`Email: ${worker.user.email}`);
    doc.text(`Account: ${worker.workforceAccount.displayName} (${worker.workforceAccount.type})`);
    doc.text(`Period: ${periodStart.toLocaleDateString("en-CA")} — ${periodEnd.toLocaleDateString("en-CA")}`);
    doc.moveDown(1);

    // Table
    const colDate = 50;
    const colSite = 140;
    const colAmount = 420;
    const colStatus = 500;
    const rowH = 20;

    doc.font("Helvetica-Bold").fontSize(9);
    doc.text("Date", colDate, doc.y);
    doc.text("Site", colSite, doc.y - rowH + 2);
    doc.text("Amount", colAmount, doc.y - rowH + 2);
    doc.text("Status", colStatus, doc.y - rowH + 2);
    doc.moveTo(50, doc.y + 4).lineTo(560, doc.y + 4).stroke();
    doc.moveDown(0.5);

    doc.font("Helvetica").fontSize(9);
    for (const job of jobs) {
      const y = doc.y;
      doc.text(new Date(job.scheduledStart).toLocaleDateString("en-CA"), colDate, y);
      doc.text(job.site.name.slice(0, 40), colSite, y);
      doc.text(`$${(job.payoutAmountCents / 100).toFixed(2)}`, colAmount, y);
      doc.text(job.status === "PAID" ? "Paid" : "Pending", colStatus, y);
      doc.moveDown(0.3);
    }

    if (jobs.length === 0) {
      doc.text("No jobs in this period.", colDate, doc.y);
    }

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(560, doc.y).stroke();
    doc.moveDown(0.5);

    doc.font("Helvetica-Bold");
    doc.text(`Total: $${(totalCents / 100).toFixed(2)}`, colAmount, doc.y);
    doc.moveDown(0.3);
    doc.font("Helvetica");
    doc.text(`Paid: $${(paidCents / 100).toFixed(2)}`, colAmount, doc.y);
    doc.text(`Pending: $${((totalCents - paidCents) / 100).toFixed(2)}`, colAmount, doc.y + 14);

    doc.moveDown(3);
    doc.fontSize(8).text("This is a pay statement generated by BLVCKSHELL Portal. For questions, contact your administrator.", 50, doc.y, { width: 500 });

    doc.end();
    const buffer = await done;

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="pay-statement-${month}.pdf"`,
      },
    });
  } catch (error) {
    logError(error, { where: "api:worker/paystub" });
    return NextResponse.json({ error: "Failed to generate pay statement" }, { status: 500 });
  }
}
