// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import dotenv from "dotenv";

// Load root .env first (single env for portal + marketing)
dotenv.config({ path: path.resolve(process.cwd(), "../.env") });
dotenv.config(); // then portal/.env if present

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Actions uses DATABASE_URL (pooler, IPv4). DIRECT_URL is optional for local IPv6 direct.
  datasource: {
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
} as Parameters<typeof defineConfig>[0]);
